/* eslint-disable @typescript-eslint/no-explicit-any */
import * as grpc from '@grpc/grpc-js';
import { ProtoLoader, INLogger } from '@inv2/common';
// import { ProtoGrpcType } from './interfaces/payment'; // generated by ts-proto or similar
import { TYPES } from '../business/types';
import { inject, injectable } from 'inversify';
import { GPCPaymentService } from './services/grpc.payment.service';

@injectable()
export class GrpcServer {
   private server: grpc.Server;

   constructor(
      @inject(TYPES.GPCPaymentService)
      private readonly gpcPaymentService: GPCPaymentService
   ) {
      this.server = new grpc.Server();
   }

   public async start(port: number): Promise<void> {
      // Load all proto services
      const financeProto = ProtoLoader.loadProto('payment.proto');
      // Add more proto files as needed

      // Add services
      const financeGrpc = financeProto as grpc.GrpcObject;
      this.server.addService(
         (financeGrpc.finance as any).payment.PaymentService.service,
         {
            InitializePayment: this.gpcPaymentService.InitializePayment,
         }
      );

      return new Promise((resolve, reject) => {
         this.server.bindAsync(
            `0.0.0.0:${port}`,
            grpc.ServerCredentials.createInsecure(),
            (err: any, boundPort: number) => {
               if (err) {
                  reject(err);
                  return;
               }
               INLogger.log.info(`gRPC server running on port ${boundPort}`);
               resolve();
            }
         );
      });
   }

   public stop(): Promise<void> {
      return new Promise((resolve) => {
         this.server.tryShutdown(() => {
            INLogger.log.info('gRPC server stopped');
            resolve();
         });
      });
   }
}