// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v3.19.1
// source: holiday.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "common.holiday";

export interface DateRequest {
  /** format: YYYY-MM-DD */
  date: string;
}

export interface BoolResponse {
  value: boolean;
}

export interface DateResponse {
  /** format: YYYY-MM-DD */
  date: string;
}

export interface Holiday {
  id: string;
  name: string;
  startDate: string;
  endDate: string;
  isObserved: boolean;
}

export interface HolidayListResponse {
  holidays: Holiday[];
}

export interface Empty {
}

function createBaseDateRequest(): DateRequest {
  return { date: "" };
}

export const DateRequest: MessageFns<DateRequest> = {
  encode(message: DateRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.date !== "") {
      writer.uint32(10).string(message.date);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DateRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDateRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.date = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DateRequest {
    return { date: isSet(object.date) ? globalThis.String(object.date) : "" };
  },

  toJSON(message: DateRequest): unknown {
    const obj: any = {};
    if (message.date !== "") {
      obj.date = message.date;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DateRequest>, I>>(base?: I): DateRequest {
    return DateRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DateRequest>, I>>(object: I): DateRequest {
    const message = createBaseDateRequest();
    message.date = object.date ?? "";
    return message;
  },
};

function createBaseBoolResponse(): BoolResponse {
  return { value: false };
}

export const BoolResponse: MessageFns<BoolResponse> = {
  encode(message: BoolResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.value !== false) {
      writer.uint32(8).bool(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BoolResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBoolResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.value = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): BoolResponse {
    return { value: isSet(object.value) ? globalThis.Boolean(object.value) : false };
  },

  toJSON(message: BoolResponse): unknown {
    const obj: any = {};
    if (message.value !== false) {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BoolResponse>, I>>(base?: I): BoolResponse {
    return BoolResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BoolResponse>, I>>(object: I): BoolResponse {
    const message = createBaseBoolResponse();
    message.value = object.value ?? false;
    return message;
  },
};

function createBaseDateResponse(): DateResponse {
  return { date: "" };
}

export const DateResponse: MessageFns<DateResponse> = {
  encode(message: DateResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.date !== "") {
      writer.uint32(10).string(message.date);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DateResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDateResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.date = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DateResponse {
    return { date: isSet(object.date) ? globalThis.String(object.date) : "" };
  },

  toJSON(message: DateResponse): unknown {
    const obj: any = {};
    if (message.date !== "") {
      obj.date = message.date;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DateResponse>, I>>(base?: I): DateResponse {
    return DateResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DateResponse>, I>>(object: I): DateResponse {
    const message = createBaseDateResponse();
    message.date = object.date ?? "";
    return message;
  },
};

function createBaseHoliday(): Holiday {
  return { id: "", name: "", startDate: "", endDate: "", isObserved: false };
}

export const Holiday: MessageFns<Holiday> = {
  encode(message: Holiday, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.startDate !== "") {
      writer.uint32(26).string(message.startDate);
    }
    if (message.endDate !== "") {
      writer.uint32(34).string(message.endDate);
    }
    if (message.isObserved !== false) {
      writer.uint32(40).bool(message.isObserved);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Holiday {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHoliday();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.startDate = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.endDate = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.isObserved = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Holiday {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      startDate: isSet(object.startDate) ? globalThis.String(object.startDate) : "",
      endDate: isSet(object.endDate) ? globalThis.String(object.endDate) : "",
      isObserved: isSet(object.isObserved) ? globalThis.Boolean(object.isObserved) : false,
    };
  },

  toJSON(message: Holiday): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.startDate !== "") {
      obj.startDate = message.startDate;
    }
    if (message.endDate !== "") {
      obj.endDate = message.endDate;
    }
    if (message.isObserved !== false) {
      obj.isObserved = message.isObserved;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Holiday>, I>>(base?: I): Holiday {
    return Holiday.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Holiday>, I>>(object: I): Holiday {
    const message = createBaseHoliday();
    message.id = object.id ?? "";
    message.name = object.name ?? "";
    message.startDate = object.startDate ?? "";
    message.endDate = object.endDate ?? "";
    message.isObserved = object.isObserved ?? false;
    return message;
  },
};

function createBaseHolidayListResponse(): HolidayListResponse {
  return { holidays: [] };
}

export const HolidayListResponse: MessageFns<HolidayListResponse> = {
  encode(message: HolidayListResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.holidays) {
      Holiday.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HolidayListResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHolidayListResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.holidays.push(Holiday.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HolidayListResponse {
    return {
      holidays: globalThis.Array.isArray(object?.holidays) ? object.holidays.map((e: any) => Holiday.fromJSON(e)) : [],
    };
  },

  toJSON(message: HolidayListResponse): unknown {
    const obj: any = {};
    if (message.holidays?.length) {
      obj.holidays = message.holidays.map((e) => Holiday.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HolidayListResponse>, I>>(base?: I): HolidayListResponse {
    return HolidayListResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HolidayListResponse>, I>>(object: I): HolidayListResponse {
    const message = createBaseHolidayListResponse();
    message.holidays = object.holidays?.map((e) => Holiday.fromPartial(e)) || [];
    return message;
  },
};

function createBaseEmpty(): Empty {
  return {};
}

export const Empty: MessageFns<Empty> = {
  encode(_: Empty, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Empty {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEmpty();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): Empty {
    return {};
  },

  toJSON(_: Empty): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<Empty>, I>>(base?: I): Empty {
    return Empty.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Empty>, I>>(_: I): Empty {
    const message = createBaseEmpty();
    return message;
  },
};

export interface HolidayService {
  IsHoliday(request: DateRequest): Promise<BoolResponse>;
  GetNextBusinessDay(request: DateRequest): Promise<DateResponse>;
  GetPreviousBusinessDay(request: DateRequest): Promise<DateResponse>;
  GetHolidayList(request: Empty): Promise<HolidayListResponse>;
}

export const HolidayServiceServiceName = "common.holiday.HolidayService";
export class HolidayServiceClientImpl implements HolidayService {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || HolidayServiceServiceName;
    this.rpc = rpc;
    this.IsHoliday = this.IsHoliday.bind(this);
    this.GetNextBusinessDay = this.GetNextBusinessDay.bind(this);
    this.GetPreviousBusinessDay = this.GetPreviousBusinessDay.bind(this);
    this.GetHolidayList = this.GetHolidayList.bind(this);
  }
  IsHoliday(request: DateRequest): Promise<BoolResponse> {
    const data = DateRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "IsHoliday", data);
    return promise.then((data) => BoolResponse.decode(new BinaryReader(data)));
  }

  GetNextBusinessDay(request: DateRequest): Promise<DateResponse> {
    const data = DateRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetNextBusinessDay", data);
    return promise.then((data) => DateResponse.decode(new BinaryReader(data)));
  }

  GetPreviousBusinessDay(request: DateRequest): Promise<DateResponse> {
    const data = DateRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetPreviousBusinessDay", data);
    return promise.then((data) => DateResponse.decode(new BinaryReader(data)));
  }

  GetHolidayList(request: Empty): Promise<HolidayListResponse> {
    const data = Empty.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetHolidayList", data);
    return promise.then((data) => HolidayListResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
